stages:
    - centos6
    # - python26
    - python27
    - python34

.python26:
    stage: python26
    image: yarara/python-2.6.9:v1
    when: always
    script:
        - python setup.py clean build test

centos6:
    stage: centos6
    image: centos:6
    when: always
    script:
        - yum upgrade -y
        - yum groupinstall -y "Development tools"
        - yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
        - yum install -y git python-devel openssl-devel openssl python-setuptools python-twisted python-unittest2
        - sh add-swig-to-centos.sh
        - python setup.py clean build test

python27:
    stage: python27
    image: python:2.7
    when: always
    script:
        - apt-get update -q -y
        - apt-get install -y swig libssl-dev libssl1.0.0 python-dev openssl python-twisted python-setuptools
        - python setup.py clean build test

python34:
    stage: python34
    image: python:3.4
    when: always
    allow_failure: yes
    script:
        - apt-get update -q -y
        - apt-get install -y swig libssl-dev libssl1.0.0 python3-dev openssl python3-setuptools
        - easy_install3 Twisted
        - python3 setup.py clean build test

.pypy:
    stage: pypy
    image: pypy:2
    when: always
    allow_failure: yes
    script:
        - if [ \! -f /etc/apt/sources.list.d/jessie-backports.list ] ;
          echo 'deb http://ftp.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/jessie-backports.list
          ; fi
        - apt-get update -q -y
        - apt-get install -y swig libssl-dev libssl1.0.0 pypy-dev openssl pypy-setuptools
        - easy_install Twisted
        - pypy setup.py clean build test
